- name: 1_install_microk8s.yaml
  hosts: rpi
  remote_user: ubuntu
  tasks:
#    - name: Install microk8s version 1.19 from snap module
#      snap:
#        name: microk8s
#        classic: yes
#        channel: 1.19
#      remote_user: root
#TODO - Change the channel below to 1.19.3, once stable, should have fix from https://github.com/ubuntu/microk8s/issues/784 implemented
    - name: Install microk8s version 1.19 from cli
      shell: |
        set timeout 1200
        snap install microk8s --classic --channel=1.19/stable; echo $?
      register: result
      until: result.stdout.find("0") != -1
      retries: 3
      delay: 1200
      remote_user: root

    - name: Wait until microk8s binary is available to check status
      wait_for:
        path: /snap/bin/microk8s
      remote_user: root

    - name: Check for microk8s successful install
      shell: |
        microk8s status --wait-ready
      remote_user: root

    - name: Setup ubuntu user for microk8s access
      shell: |
        usermod -a -G microk8s ubuntu
        cp -R /root/.kube /home/ubuntu/
        chown -f -R ubuntu /home/ubuntu/.kube
      remote_user: root

    - name: Make sure user ubuntu can manipulate microk8s
      shell: |
        microk8s status

