- name: 6_install_telegraf.yaml
  hosts: rpi
  remote_user: ubuntu
  tasks:
    - name: Create auth secret, install telegraf via helm, patch to have fourth IP in metallb range as assigned IP
      shell: |
        set timeout 1200
        . /boot/firmware/rpi-vars.txt
        microk8s helm3 install --timeout 20m rpi-telegraf influxdata/telegraf --set image.tag=1.15 --set service.type=LoadBalancer,persistence.enabled=true,persistence.size=1Gi,config.inputs=null,config.outputs=null -n solarmon
        microk8s kubectl patch svc rpi-telegraf -p '{"spec": {"loadBalancerIP": "{{ internal_network_metallb_start_ip  | ipmath(3) }}"}}' -n solarmon

    - name: Check to make sure helm install of telegraf succeeded
      shell: |
        microk8s helm3 ls -n solarmon | grep rpi-telegraf | grep -w deployed | wc -l
      register: result
      until: result.stdout.find("1") != -1
      retries: 180
      delay: 10

    - name: Update /etc/hosts file for telegraf record
      shell: |
        cat << EOF >> /etc/hosts
        {{ internal_network_metallb_start_ip | ipmath(3) }} rpi-telegraf.{{ microk8s_info_top_domain }}

        EOF
      remote_user: root

    - name: Restart dnsmasq
      service:
        name: dnsmasq
        state: started
      remote_user: root

    - name: Check for running status of telegraf pod
      shell: |
        microk8s kubectl get pod -n solarmon | grep rpi-telegraf | grep -w Running| wc -l
      register: result
      until: result.stdout.find("1") != -1
      retries: 180
      delay: 10